In [2]:
import numpy as np

In [4]:
# vectorization
arr = np.array([1,2,3,4,5,6])
result = arr**2
print(result)

[ 1  4  9 16 25 36]


In [5]:
#Broadcasting
ar = np.array([1,2,3,4,5,6 
result = ar+10    #10 added to all element of array
print(result)

[11 12 13 14 15 16]


In [8]:
#broadcasting 2d array into 1d array
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([1,2,3])
result = a1 + a2     #this [1,2,3] is added to all element  of 2d array
# --- broadcasting a2 to a1
print(result)

[[2 4 6]
 [5 7 9]]


In [10]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized_form = (data - mean)/std
print(normalized_form)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


# Mathematical functions in Numpy

In [18]:
arr = np.array([2,4,6,8,10])
np.mean(arr)     #calculating mean
np.std(arr)      #calculating standard deviation
np.var(arr)       #calculating variance
np.argmin(arr)    #index of minimun value
np.argmax(arr)    #index of max value

np.int64(4)