# Array Dimension

In [1]:
import numpy as np
#one dimensional array
d1 = np.array([1,2,3,4,5])
d1# one-dimensional

array([1, 2, 3, 4, 5])

In [3]:
#2d Array
d2 = np.array([[1,2,3],[4,5,6]])
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.zeros((2, 2))    # 3x3 array of zeros
np.ones((2, 4))     # 2x4 array of ones
np.full((2, 2), 7)  # 2x2 array filled with 7
np.eye(4)           # 4x4 identity matrix
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (from first value 1 to 10 increasing by 2)
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Checking Array Properties
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr.shape)   #printing shape of array
print (arr.size)   #printing size of array
print(arr.ndim)    #dimension of array
print(arr.dtype     #

# Changing Data Types


In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60]], dtype = "float32")   #Explicit type
arr

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [16]:
arr_int = arr.astype(np.int32)
arr_int

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)

# Reshaping and Flattening Arrays

In [29]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr.shape 
# reshaping a 2,3 array into 3,2
reshaped = arr.reshape((3,2))
reshaped

array([[10, 20],
       [30, 40],
       [50, 60]])

In [31]:
arr = np.array([[10, 20, 30], [40, 50, 60]])  
#flattern converts into 1D
arr.flatten()

array([10, 20, 30, 40, 50, 60])

# Indexing & Slicing

In [1]:
import numpy as np
#indexing
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0])  
print(arr[-1])


10
70


In [2]:
print(arr[2::2])  #taking every 2 vlaues
sliced = arr[1:4].copy()  #creating copy of sliced data
sliced[0] = 11             #slice provides view only not duplicate
print(arr)
print(sliced)


[30 50 70]
[10 20 30 40 50 60 70]
[11 30 40]


In [7]:
arrr = np.array([1,4,5,6,7,5,4,5,8,7,])
inx = [1,9,7]     #selecting from these indexes
print(arrr[inx])

[4 7 5]


# Boolean Masking

In [9]:
ar = np.array([1,4,5,6,7,5,4,5,8,7,])
ar[ar>5]  #printing greater value then 5

array([6, 7, 8, 7])

# Axes in Array

In [3]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
np.sum(arr, axis=0)   #axis 0 means row     axis 1 means column

array([12, 15, 18])

In [8]:
arr[0:2, 1:3] 

array([[2, 3],
       [5, 6]])

In [10]:
print(arr[1,2])   #row index 1 column index 2

6


# Indexing in 3D Arrays

In [13]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D[0,1,2])   #from index 0, row index 1 and column 3   (depth, rows, columns)
print(arr3D[:,1,:])

6
[[ 4  5  6]
 [10 11 12]]


In [16]:
#Changing Data Along an Axis
ar = np.array([[1,2,3],
                [4,5,6]])
ar[0:,1] = 0
ar

array([[1, 0, 3],
       [4, 0, 6]])

# Data Types in NumPy

In [ ]:
'''int32, int64: Integer types with different bit sizes.
float32, float64: Floating-point types with different precision.
bool: Boolean data type.
complex64, complex128: Complex number types.
object: For storing objects (e.g., Python objects, strings). '''

In [7]:
import numpy as np
#Converting Data type
ar = np.array([1.5, 2.7, 3.9])
print(ar.dtype) 

arr_int = ar.astype("int32")  # Converting float to int
print(arr_int)    
print(arr_int.dtype)  

float64
[1 2 3]
int32


In [8]:
#downcasting
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  
print(arr_small.dtype)  

[1000000 2000000 3000000]
int32


# String Data Type

In [11]:
str_arr = np.array(["apple", "banana", "orange"], dtype="U10")
str_arr

array(['apple', 'banana', 'orange'], dtype='<U10')

In [14]:
#complex number
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex64')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]
